# Generated by Django 5.1.2 on 2024-10-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_categoria_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unid_Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('siglas', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
