# Generated by Django 5.1.2 on 2024-10-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_unid_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unid_org'),
        ),
    ]
