# Generated by Django 5.1.2 on 2024-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_user_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_con_copia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_emisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_participante',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('supervisor', 'Supervisor'), ('viewer', 'Visualizador')], max_length=20),
        ),
    ]
