# Generated by Django 5.1.2 on 2024-10-21 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_concopia_emisor_participante_responsable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_emision', models.DateField()),
                ('fecha_cumplimiento', models.DateField()),
                ('proceso', models.CharField(choices=[('Chequeo diario', 'Chequeo diario'), ('Operaciones', 'Operaciones'), ('Seguridad y protección', 'Seguridad y protección'), ('Inversiones', 'Inversiones'), ('Comercial', 'Comercial'), ('Logística y servicios', 'Logística y servicios')], max_length=50)),
                ('contenido', models.TextField()),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria')),
                ('con_copia', models.ManyToManyField(blank=True, related_name='acuerdos_con_copia', to=settings.AUTH_USER_MODEL)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos_emisor', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='acuerdos_participantes', to=settings.AUTH_USER_MODEL)),
                ('procedencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.unid_org')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
