# Generated by Django 5.1.2 on 2024-10-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acuerdos', '0002_acuerdo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='proceso',
            field=models.CharField(choices=[('Chequeo diario', 'Chequeo diario'), ('Operaciones', 'Operaciones'), ('Seguridad y protección', 'Seguridad y protección'), ('Inversiones', 'Inversiones'), ('Comercial', 'Comercial'), ('Logística y servicios', 'Logística y servicios'), ('Otro', 'Otro')], max_length=50),
        ),
    ]
